name: 'run-tests'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_TEST_USER_EMAIL: 'test@test.io'
      PUBLIC_TEST_USER_PASSWORD: 'test1234'
      NODE_ENV: 'test'
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase init
      - run: supabase start
      - run: npm run env:local
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
